name: Android build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up JDK
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      # Cache
      - uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: ${{ runner.os }}-gradle-

      # Permissions for Gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # Build
      - name: Build with Gradle
        run: ./gradlew build bundleRelease
        env:
          NSR_KEYS_TRAVEL_API: ${{ secrets.NSR_KEYS_TRAVEL_API }}
          NSR_KEYS_APP_API: ${{ secrets.NSR_KEYS_APP_API }}
          ANDROID_STORE_PASSWORD: ${{ secrets.ANDROID_STORE_PASSWORD }}
          ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
          ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}

      # Move artifacts
      - name: Move artifacts
        run: |
          cd app/build/outputs
          mkdir out
          find bundle -type f -exec sh -c 'mv "$@" out' _ {} +
          cd ../../..

      # Upload artifacts
      - uses: actions/upload-artifact@v2
        with:
          name: app-release
          path: app/build/outputs/out/app-*-release.aab
          if-no-files-found: error
